name: Build & Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        name: Clonar repositorio

      - name: Construir imagen
        run: docker build -t sauldiazfonseca/pet-radar-api:latest .

      - name: Taggear imagen con commit
        run: docker tag sauldiazfonseca/pet-radar-api:latest sauldiazfonseca/pet-radar-api:${{github.sha}}

      - name: Docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push sauldiazfonseca/pet-radar-api:${{github.sha}}

  
